### ISSUE TITLE
How to train binding prediction model with only BA data?

### ISSUE THREAD

**Issue by KiAkize** [s6juncheng/BERTMHC#1]
I may ask two questions about binding prediction task.

BA data does not have a masslabel and cannot form an input data format like `train.csv`. I found that the train function in `utils_model.py` adds aff_loss and mass_loss together as a loss function to update the parameters. 
**Q1**: How to use only BD2016, the dataset in NetMHCIIpan3.2 which are BA datas to train BERTMHC? 

I found that the calculation of auROC and AUPR in `utils_model.py` is not calculated separately according to allele.
**Q2**:  How does the experiment in Figure 3 in the paper do it?

**Comment by s6juncheng** [comment]
Hi, @KiAkize Thanks for checking out our tool.

Q1: To train on BA only data, you should use set alpha=0 and deconvolution false (`--alpha 0 --deconvolution False` argument in the command line). In the input data, you could use some arbitrary label for `masslabel`, e.g. set all to 0. Since `alpha=0`, the masslabel will not contribute to the loss (weighted 0). In addition, make sure you have `[allele, mhc, peptide, label]` columns in your input data.

Indeed this part of implementation could be improved. 

Q2: Per allele evaluation is done after finishing the training and evaluated post-hoc on the held-out data. i.e. run prediction on all held-out data, evaluate per allele. 

Hope this is clear, feel free to follow up if otherwise.

**Comment by KiAkize** [comment]
I am not sure if there can only be one type of allele such as DRB1_0404 in the csv file to input during the train and predict process. I tried to use a csv file with multiple alleles to train and report errors:
```
Traceback (most recent call last):
  File "/home/quw/anaconda3/bin/bertmhc", line 8, in <module>
    sys.exit(main())
  File "/home/quw/anaconda3/lib/python3.8/site-packages/bertmhc/cli.py", line 132, in main
    args.func(args)
  File "/home/quw/anaconda3/lib/python3.8/site-packages/bertmhc/cli.py", line 234, in train_bertmhc
    train_metrics = train(model, optimizer, train_data, device, aff_criterion, mass_criterion, args.alpha, scheduler)
  File "/home/quw/anaconda3/lib/python3.8/site-packages/bertmhc/utils_model.py", line 296, in train
    logits, targets = model(**batch)
  File "/home/quw/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/quw/anaconda3/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 151, in forward
    replicas = self.replicate(self.module, self.device_ids[:len(inputs)])
  File "/home/quw/anaconda3/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 156, in replicate
    return replicate(module, device_ids, not torch.is_grad_enabled())
  File "/home/quw/anaconda3/lib/python3.8/site-packages/torch/nn/parallel/replicate.py", line 88, in replicate
    param_copies = _broadcast_coalesced_reshape(params, devices, detach)
  File "/home/quw/anaconda3/lib/python3.8/site-packages/torch/nn/parallel/replicate.py", line 71, in _broadcast_coalesced_reshape
    tensor_copies = Broadcast.apply(devices, *tensors)
  File "/home/quw/anaconda3/lib/python3.8/site-packages/torch/nn/parallel/_functions.py", line 21, in forward
    outputs = comm.broadcast_coalesced(inputs, ctx.target_gpus)
  File "/home/quw/anaconda3/lib/python3.8/site-packages/torch/cuda/comm.py", line 39, in broadcast_coalesced
    return torch._C._broadcast_coalesced(tensors, devices, buffer_size)
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 3; 11.91 GiB total capacity; 24.10 MiB already allocated; 3.94 MiB free; 28.00 MiB reserved in total by PyTorch) (malloc at /pytorch/c10/cuda/CUDACachingAllocator.cpp:289)
```

When I use the provided train.csv file, I can train and save model.pt normally, and use eval.csv to predict normally. But loading the model.pt to predict a csv file containing multiple alleles resulted in the same error.
```
Traceback (most recent call last):
  File "/home/quw/anaconda3/bin/bertmhc", line 8, in <module>
    sys.exit(main())
  File "/home/quw/anaconda3/lib/python3.8/site-packages/bertmhc/cli.py", line 132, in main
    args.func(args)
  File "/home/quw/anaconda3/lib/python3.8/site-packages/bertmhc/cli.py", line 272, in predict
    logits, _ = model(**batch)
  File "/home/quw/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/quw/anaconda3/lib/python3.8/site-packages/bertmhc/bertmhc.py", line 79, in forward
    outputs = self.bert(input_ids, input_mask=input_mask)
  File "/home/quw/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/quw/anaconda3/lib/python3.8/site-packages/tape/models/modeling_bert.py", line 447, in forward
    encoder_outputs = self.encoder(embedding_output,
  File "/home/quw/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/quw/anaconda3/lib/python3.8/site-packages/tape/models/modeling_bert.py", line 346, in forward
    layer_outputs = layer_module(hidden_states, attention_mask)
  File "/home/quw/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/quw/anaconda3/lib/python3.8/site-packages/tape/models/modeling_bert.py", line 287, in forward
    intermediate_output = self.intermediate(attention_output)
  File "/home/quw/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/quw/anaconda3/lib/python3.8/site-packages/tape/models/modeling_bert.py", line 259, in forward
    hidden_states = self.intermediate_act_fn(hidden_states)
  File "/home/quw/anaconda3/lib/python3.8/site-packages/tape/models/modeling_utils.py", line 624, in gelu
    return x * 0.5 * (1.0 + torch.erf(x / math.sqrt(2.0)))
RuntimeError: CUDA out of memory. Tried to allocate 348.00 MiB (GPU 0; 11.91 GiB total capacity; 11.07 GiB already allocated; 16.94 MiB free; 11.34 GiB reserved in total by PyTorch)
```

**Comment by s6juncheng** [comment]
It can run will many alleles as long as the `mhc` column is provided. As the error message says, you have a cuda memory issue. Try to check whether there are other processes running on the same GPU. You could also try to reduce the `--batch_size` option.

**Comment by KiAkize** [comment]
The problem is found, it is caused by the larger `batch_size` of the default setting. Thank you.

**Comment by s6juncheng** [comment]
Great it worked, thanks.

**Comment by KiAkize** [comment]
I tried to do the 5cv experiment in Figure 3. I used `--train train_i.csv --eval test_i.csv` to train the binding prediction model and make predictions accordingly. The command used was set to `--data test_i.csv --task binding`. I found that the value of `bertmhc_pred` in `output.csv` is around 0.5, this value as logit does not match binding affinity?

**Comment by s6juncheng** [comment]
`--data` is a folder where you find the training test data (maybe `train_i.csv`, `test_i.csv`) in your case. Make sure you also running on real data, the test data provided is synthesized (just to test model installation), will not produce meaningful results.
```
    train_parser.add_argument('--data', type=str, default='tests/data/',
                        help='location of the data corpus')
```
Please try to read the command-line help. `bertmhc train --help`
