### ISSUE TITLE
Unit test fails

### ISSUE THREAD

**Issue by ikizhvatov** [s6juncheng/BERTMHC#4]
* BERTMHC version: git 33023352e
* Python version: 3.6
* Operating System: Linux

### What I Did

```
python -m unittest tests.test_bertmhc.test_bert
  0%|                                                                                                                                                                           | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  [cut]
  File "tests/test_bertmhc.py", line 92, in test_bert
    train(model, optimizer, train_data, device, aff_criterion, mass_criterion, alpha, scheduler)
  File "bertmhc/utils_model.py", line 306, in train
    mass_loss *= instance_weights[mass_valid]
RuntimeError: output with shape [] doesn't match the broadcast shape [26]

```

**Comment by s6juncheng** [comment]
Thanks, I pushed the fix, please update the repo.

**Comment by ikizhvatov** [comment]
Now after 4 epochs:
```
TypeError: calling <function test_bert at 0x7f460798c8c8> returned {'val_cor': 0.15217391304347824, 'val_auc': 0.6013986013986015, 'val_ap': 0.6347270579929951, 'val_ap_sa': 0.7749879749879751, 'val_mass_auc': 0.37037037037037035, 'val_loss': 0.02872378999988238}, not a test
```

**Comment by s6juncheng** [comment]
are you running `pytest`? We use `pytest`, maybe you are running `unittest`? The model is returning test metrics, looks fine for me.

**Comment by ikizhvatov** [comment]
`pytest` works, both tests passed, thank you.
